hibernate hw
MaVaYuran/andersen pull request #12
Opened 2024-09-25 21:06 UTC by MaVaYuran

2024-09-26 05:24 UTC, Alexmansar requested changes
@MaVaYuran In general doof job) But I have some general comments, so please fix them

2024-09-26 05:24 UTC, Alexmansar commented on src/main/java/hibernate/HibernateRunner.java
> +//        System.out.println(ticketDAO.getTicket(2));
don't use commented code

2024-09-26 05:24 UTC, Alexmansar commented on src/main/java/hibernate/dao/TicketDAOImpl.java
> +        }
please, use try with resources

2024-09-26 05:24 UTC, Alexmansar commented on src/main/java/hibernate/dao/TicketDAOImpl.java
> +            transaction.commit();
not needed. You don't change entity

2024-09-26 05:24 UTC, Alexmansar commented on src/main/java/hibernate/dao/TicketDAOImpl.java
> +                transaction.commit();
here its OK, because we update record

2024-09-27 19:58 UTC, MaVaYuran commented
Now all methods working

2024-09-29 06:38 UTC, Alexmansar approved these changes
@MaVaYuran Some small comments) please, fix it and merge)

2024-09-29 06:38 UTC, Alexmansar commented on src/main/java/hibernate/dao/UserDAOImpl.java
> +            user = session.get(User.class, id);
in general, you can just use
User user = session.get(User.class, id);

2024-09-29 06:38 UTC, Alexmansar commented on src/main/java/hibernate/entity/Ticket.java
> +    public void setUserId(User user) {
why setUserId?
just setUser

2024-09-30 17:30 UTC, MaVaYuran commented
Alexandr good evening, can i merge it

2024-09-30 17:37 UTC, merged