spring-boot. points 1,2
MaVaYuran/andersen pull request #15
Opened 2024-10-14 22:32 UTC by MaVaYuran

Hello. Sorry, was busy

2024-10-15 07:56 UTC, Alexmansar requested changes
@MaVaYuran please, fix small comment
and what about this part?
![image](https://github.com/user-attachments/assets/1a96c340-74c4-40fb-997c-35f0370b116f)

2024-10-15 07:56 UTC, Alexmansar commented on pom.xml
> +<!--        <spring.version>6.1.12</spring.version>-->
remove it please

2024-10-15 17:04 UTC, MaVaYuran commented
Alexandr, pls could you say something?

2024-10-15 17:08 UTC, Alexmansar requested changes
@MaVaYuran Plese, fix it and merge

until you click on the button again, no review request will come to me. 
![image](https://github.com/user-attachments/assets/5e9b8f25-217e-44a9-83e0-bbdaffb08286)

2024-10-15 17:08 UTC, Alexmansar commented on src/main/java/by/mariayuran/springboot/config/SecurityConfig.java
> +                        .requestMatchers("/tickets**").authenticated()
fis it as we chat in telegram

2024-10-16 09:01 UTC, Alexmansar approved these changes
@MaVaYuran Hi) please, merge it

2024-10-16 09:21 UTC, merged